### ISSUE TITLE
Syntax highlighting does not apply properly

### ISSUE THREAD

**Issue by preco21** [orktes/atom-react#177]
Hello, I have some trouble while using this plugin.

It seems jsx syntax highlighting does not work as I expected:

![image 001](https://cloud.githubusercontent.com/assets/4936201/16646823/37969f9a-4467-11e6-83c7-7a4032be61c3.png)

As above, when I use jsx tags without surrounding brackets (`{}`) then it seems working fine. (even, it works fine when strip off brackets on the second code) But if with surrounding brackets, it seems syntax highlighting is not applied properly. Also even it doesn't apply any autocompletion.

Anyone has some idea about this issue?

Versions:

* Windows 10
* Atom@1.9.0-beta.0
* atom-react@0.15.0

**Comment by martip-sainsburys** [comment]
I'm seeing this too, with the latest version the syntax highlighting is not working properly

**Comment by shikelong** [comment]
+ 1

**Comment by shikelong** [comment]
me too

**Comment by martip-sainsburys** [comment]
@orktes could you take a look??

**Comment by fpaeslima** [comment]
I have the same problem but since I have two Atom's versions installed I tested with 1.8.0 and it's working properly, both the highlight and autocomplete.

![reactsyntax](https://cloud.githubusercontent.com/assets/12243928/17375322/ceda35b8-5986-11e6-97aa-170b51eaca83.png)


Atom: **1.8.0**
Atom-React: **0.15.0**
System: **Ubuntu64 14.04 LTS**

**Comment by orktes** [comment]
Sorry for delay was on vocation. Should be fixed now https://github.com/orktes/atom-react/issues/188
